services:
  tests:
    build:
      context: .
    container_name: fophelp-tests
    volumes:
      - ./allure-results:/tests/allure-results
    depends_on:
      - allure
    environment:
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    command: ["npx", "playwright", "test"]

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: "1"

  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure-ui
    ports:
      - "5252:5252"
    environment:
      - ALLURE_DOCKER_PUBLIC_API_URL=http://localhost:5050
      - ALLURE_DOCKER_PUBLIC_HOST=localhost
    depends_on:
      - allure